import type { ArchipelagoLocale } from './types';

const COPY = {
  ko: {
    eyebrow: 'SIDEQUESTLAB · LIVING ARCHIPELAGO',
    titleLead: '살아 움직이는',
    titleTail: '제품 군도',
    intro: '세 개의 프로젝트 섬과 공개 가능한 최근 활동을 한눈에 탐험하세요.',
    introPhrase: '최근 활동을',
    truth: '승인된 공개 스냅샷을 바탕으로 재구성한 장면입니다.',
    previewDisclosure: '미리보기 · 표시 상태는 제품 운영 상태를 변경하지 않습니다.',
    projects: '프로젝트 섬',
    activeCrew: '스냅샷 기반 가이드',
    proofMode: '공개 데이터 모드',
    choose: '탐험할 프로젝트 섬 선택',
    selected: '선택한 섬',
    details: '프로젝트 자세히',
    visit: '서비스 방문',
    guide: 'Crew 안내',
    close: '닫기',
    activity: '최근 공개 활동',
    motion: '움직임',
    motionSystem: '시스템',
    motionReduced: '줄임',
    motionOff: '끔',
    demoState: '상태 미리보기',
    fleetFeed: 'Fleet Feed',
    fleetSummary: '세 프로젝트 섬의 공개 상태와 탐험 경로',
    fleetSummaryPhrase: '공개 상태와 탐험 경로',
    tabs: ['프로젝트', '지도', 'Wayfarer', '기록'] as const,
    noCrew: '공개된 Wayfarer 활동 없음',
    guideTitle: '두 AI Wayfarer를 만나보세요',
    guideBody: [
      'Code Engineer는 제품을 만들고, QA Navigator는 경로와 품질을 확인합니다.',
      '이들은 공개 상태를 설명하는 상징적 안내자입니다.',
    ] as const,
    mapLabel: '세 프로젝트 섬의 접근 가능한 지도',
    route: 'Navigator 이동 경로',
    logbook: '공개 기록',
    logbookBody: '표시된 버전과 진행 상태는 승인된 데모 스냅샷에서 가져왔습니다.',
    updated: '공개 정보 업데이트',
    outcome: '공개 결과',
    evidence: 'GitHub 근거 보기',
    unavailableLive: '공개 서비스 링크 없음',
    unavailableEvidence: '공개 근거 링크 없음',
    symbolicGuides: '공개된 활동 기록이 없어 상징적 안내 상태로 표시합니다.',
    publishedSnapshot: '승인된 공개 스냅샷',
    overview: '전체 군도로 돌아가기',
    workZone: '선택한 섬의 공개 작업 구역',
    observing: '공개 상태 관찰 중',
    simulatedState: '미리보기 전용 표시 상태',
    lifecycleLabel: '개발 단계',
    progressLabel: '진행률',
    versionLabel: '버전',
    projectStates: {
      IDEA: '아이디어',
      PLANNING: '계획',
      DESIGNING: '설계',
      BUILDING: '개발',
      REVIEWING: '검토',
      TESTING: '검증',
      WAITING_FOR_RELEASE: '출시 승인 대기',
      DEPLOYING: '배포',
      OPERATING: '운영',
      MAINTENANCE: '유지보수',
      BLOCKED: '진행 차단',
      PAUSED: '일시 중단',
      ARCHIVED: '보관',
    },
    healthStates: {
      NORMAL: '정상',
      CAUTION: '주의',
      AT_RISK: '위험',
      BLOCKED: '차단',
      UNKNOWN: '확인 필요',
    },
    guideStates: {
      IDLE: '대기',
      PLANNING: '계획 중',
      WORKING: '제작 중',
      REVIEWING: '검토 중',
      TESTING: '검증 중',
      WAITING_FOR_HUMAN: '사람의 확인 대기',
      BLOCKED: '진행 차단',
      COMPLETED: '완료',
      MONITORING: '관찰 중',
    },
  },
  en: {
    eyebrow: 'SIDEQUESTLAB · LIVING ARCHIPELAGO',
    titleLead: 'A living archipelago',
    titleTail: 'of products',
    intro: 'Explore three project islands and their latest public activity at a glance.',
    introPhrase: 'latest public activity',
    truth: 'A reconstructed scene based on an approved public snapshot.',
    previewDisclosure: 'Preview · display controls do not change product operations.',
    projects: 'Project islands',
    activeCrew: 'Snapshot-backed guides',
    proofMode: 'Public data mode',
    choose: 'Choose a project island to explore',
    selected: 'Selected island',
    details: 'Project details',
    visit: 'Visit service',
    guide: 'Crew guide',
    close: 'Close',
    activity: 'Latest public activity',
    motion: 'Motion',
    motionSystem: 'System',
    motionReduced: 'Reduced',
    motionOff: 'Off',
    demoState: 'State preview',
    fleetFeed: 'Fleet Feed',
    fleetSummary: 'Public status and routes for three project islands',
    fleetSummaryPhrase: 'project islands',
    tabs: ['Projects', 'Map', 'Wayfarers', 'Logbook'] as const,
    noCrew: 'No published Wayfarer activity is available',
    guideTitle: 'Meet the two AI Wayfarers',
    guideBody: [
      'The Code Engineer builds the product while the QA Navigator checks its route and quality.',
      'They are symbolic guides to the published state.',
    ] as const,
    mapLabel: 'Accessible map of three project islands',
    route: 'Navigator route',
    logbook: 'Public logbook',
    logbookBody: 'The displayed versions and progress states come from an approved demo snapshot.',
    updated: 'Public info updated',
    outcome: 'Public outcome',
    evidence: 'View GitHub evidence',
    unavailableLive: 'No public service link',
    unavailableEvidence: 'No public evidence link',
    symbolicGuides: 'No published activity is available; symbolic guide states are shown.',
    publishedSnapshot: 'Approved public snapshot',
    overview: 'Return to all islands',
    workZone: 'Selected island public work zone',
    observing: 'Observing published state',
    simulatedState: 'Preview-only simulated display state',
    lifecycleLabel: 'Lifecycle',
    progressLabel: 'Progress',
    versionLabel: 'Version',
    projectStates: {
      IDEA: 'Idea',
      PLANNING: 'Planning',
      DESIGNING: 'Designing',
      BUILDING: 'Building',
      REVIEWING: 'Reviewing',
      TESTING: 'Testing',
      WAITING_FOR_RELEASE: 'Waiting for release',
      DEPLOYING: 'Deploying',
      OPERATING: 'Operating',
      MAINTENANCE: 'Maintenance',
      BLOCKED: 'Blocked',
      PAUSED: 'Paused',
      ARCHIVED: 'Archived',
    },
    healthStates: {
      NORMAL: 'Normal',
      CAUTION: 'Caution',
      AT_RISK: 'At risk',
      BLOCKED: 'Blocked',
      UNKNOWN: 'Unknown',
    },
    guideStates: {
      IDLE: 'Idle',
      PLANNING: 'Planning',
      WORKING: 'Working',
      REVIEWING: 'Reviewing',
      TESTING: 'Testing',
      WAITING_FOR_HUMAN: 'Waiting for human',
      BLOCKED: 'Blocked',
      COMPLETED: 'Completed',
      MONITORING: 'Monitoring',
    },
  },
} as const;

export function getArchipelagoCopy(locale: ArchipelagoLocale) {
  return COPY[locale];
}

export type ArchipelagoCopy = ReturnType<typeof getArchipelagoCopy>;
